import type { Metadata } from "next";
import "./globals.scss";
// import { Inter, M_PLUS_1p } from "next/font/google";
// import SplashCursor from "@/components/SplashCursor";

import "yakuhanjp";
import "yakuhanjp/dist/css/yakuhanrp.css";
import "yakuhanjp/dist/css/yakuhanrp_s.css";
import SmoothScrollWrapper from "@/layout/SmoothScrollWrapper";

// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
// const mPlus1p = M_PLUS_1p({
// 	variable: "--font-mplus",
// 	weight: ["100", "300", "400", "500", "700", "800"],
// });

export const metadata: Metadata = {
	title: "Nam Dang | Portfolio 🍓",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
			// className={`${inter.variable} ${mPlus1p.variable} antialiased`}
			>
				<SmoothScrollWrapper>{children}</SmoothScrollWrapper>
				{/* <SplashCursor /> */}
			</body>
		</html>
	);
}
